name: Cleanup Old Artifacts

on:
  schedule:
    - cron: '0 3 */3 * *'  # every 3 days at 3am UTC (same as main repo)
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove old artifacts
        run: |
          # Remove directories older than 60 days
          find runs -maxdepth 1 -type d -mtime +60 -exec rm -rf {} \; 2>/dev/null || true

      - name: Commit cleanup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || {
            git commit -m "Cleanup: Remove artifacts older than 60 days"
            git push
          }
